version: '3.1'
services:
  app-wallet:
    container_name: app-wallet
    restart: always
    build:
      context: ../
      dockerfile: dockerfiles/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production

  database:
    image: postgres
    container_name: dbwallet
    environment:
      - POSTGRES_USER=walletteste
      - POSTGRES_PASSWORD=123
    ports:
      - '5432:5432'
